### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by ZixiaChen** [CaenJones/3kho-Remixed#1]
Hi I was wondering if you had discord so you can help me with coding eaglercraft 1.20.4 thanks I appreciate it.

**Comment by CaenJones** [comment]
Hello, I am sorry for responding so late. I would not like to provide my discord due to privacy and security concerns. If you are looking for people to collaborate with for making another eaglercraft server version I would talk to people on Myths community on revolt or on the official eaglercraft discord.

**Comment by ZixiaChen** [comment]
Ok

**Comment by ZixiaChen** [comment]
Thx for replying tho
